### ISSUE TITLE
status-reference-hard not registered

### ISSUE THREAD

**Issue by froemken** [TYPO3/styleguide#127] opened 2018-11-05 13:11 UTC
Hello,

if I open styleguide and click on Icons I get following error:

Oops, an error occurred!
Icon with identifier "status-reference-hard" is not registered"

I have searched a little bit in core and found out, that this icon is part of impext. After enabling this extension Icon-View works as expected.

Stefan

**Comment by lolli42** [comment] 2018-11-06 08:41
weird. thx for htis report. needs investigation.

**Comment by lolli42** [comment] 2020-08-16 09:50
That's a core bug, see https://forge.typo3.org/issues/92021. Will be fixed in v10 since the issue is not critical enough for v9 anymore. For v9, please just load ext:impexp to circumvent the issue.
Will close here.

**Closed by lolli42** 2020-08-16 09:50 UTC
